export interface IIexQuote {
  symbol: string;
  companyName: string;
  primaryExchange: string;
  calculationPrice: string;
  open: number | null;
  openTime: number | null;
  openSource?: string;
  close: number | null;
  closeTime: number | null;
  closeSource?: string;
  high: number | null;
  highTime: number | null;
  highSource?: string | null;
  low: number | null;
  lowTime: number | null;
  lowSource?: string | null;
  latestPrice: number | null;
  latestSource: string;
  latestTime: string;
  latestUpdate: number | null;
  latestVolume: number | null;
  iexRealtimePrice: number | null;
  iexRealtimeSize: number | null;
  iexLastUpdated: number | null;
  delayedPrice: number | null;
  delayedPriceTime: number | null;
  oddLotDelayedPrice: number | null;
  oddLotDelayedPriceTime: number | null;
  extendedPrice: number | null;
  extendedChange: number | null;
  extendedChangePercent: number | null;
  extendedPriceTime: number | null;
  previousClose: number | null;
  previousVolume: number | null;
  change: number | null;
  changePercent: number | null;
  volume: number;
  iexMarketPercent: number | null;
  iexVolume: number | null;
  avgTotalVolume: number;
  iexBidPrice: number | null;
  iexBidSize: number | null;
  iexAskPrice: number | null;
  iexAskSize: number | null;
  iexOpen: number | null;
  iexOpenTime: number | null;
  iexClose: number | null;
  iexCloseTime: number | null;
  marketCap: number | null;
  peRatio: number | null;
  week52High: number;
  week52Low: number;
  ytdChange: number;
  lastTradeTime: number | null;
  isUSMarketOpen?: boolean;
}
