name: CI Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - name: Add token to npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=$GITHUBTOKEN" >> .npmrc
        env:
          GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}
      - name: Install Packages
        run: npm i
      - name: Npm run test
        run: npm run test

