name: Clean Packages
# short list packages names
# gh api --jq '.[].name' -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "page: 2" -H "Per_page: 100" "/orgs/GemunIon/packages?package_type=npm" > pkglist.txt

on:
  workflow_dispatch:

jobs:
  clean:
    continue-on-error: true
    strategy:
      max-parallel: 1
      matrix:
        package: [ 'nest-js-utils',
                   'nest-js-create-middleware-module',
                   'nest-js-module-typeorm-logger',
                   'nest-js-module-helmet',
                   'nest-js-guards',
                   'nest-js-module-request-logger',
                   'collection',
                   'nest-js-module-winston-logdna',
                   'nest-js-module-mailjet',
                   'nest-js-module-throttler',
                   'nest-js-create-dynamic-module',
                   'winston-formatter',
                   'nest-js-module-passport',
                   'nest-js-module-typeorm-helpers',
                   'nest-js-module-typeorm',
                   'nest-js-module-typeorm-debug',
                   'nest-js-validators',
                   'nest-js-module-s3',
                   'nest-js-module-winston',
                   'nest-js-guards-ws',
                   'nest-js-utils-ws',
                   'nest-js-module-session',
                   'nest-js-module-metamask',
                   'nest-js-module-typeorm-postgres',
                   'nest-js-module-gee-test',
                   'nest-js-module-firebase',
                   'nest-js-module-coin-market-cap',
                   'utils-eth',
                   'nest-js-module-coin-gecko',
                   'nest-js-module-pinata-firebase',
                   'nest-js-module-infura-firebase',
                   'nest-js-module-exchange-signer',
                   'nest-js-module-nft-storage-firebase',
                   'nest-js-module-web3-storage-firebase',
                   'nest-js-module-ses',
                   'nest-js-module-secret-manager',
                   'nest-js-module-cache',
                   'nest-js-module-secret-manager-gcp',
                   'nest-js-module-secret-manager-aws',
                   'nest-js-module-secret-manager-env',
                   'nest-js-module-gcp-secret-manager',
                   'nest-js-module-iex-cloud',
                   'nest-js-module-pinata-s3',
                   'nest-js-module-intercom',
                   'nest-js-module-mailchimp',
                   'nest-js-utils-ms',
                   'nest-js-guards-gql',
                   'nest-js-module-winston-papertrail',
                   'nest-js-module-mandrill',
                   'nest-js-module-pay-pal' ]
    runs-on: ubuntu-latest

    steps:
      - name: clean package
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ matrix.package }}
          package-type: 'npm'
          min-versions-to-keep: 10
      - name: Sleep for 3 sec
        run: sleep 3s
        shell: bash
