
name: Manual release Publish --force
on:
  workflow_dispatch:

jobs:
  user-publish:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      # BEGIN INSTALL
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna to correctly version)
          # see https://stackoverflow.com/a/60184319/9285308 & https://github.com/actions/checkout
          fetch-depth: "0"
      # pulls all tags (needed for lerna to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* # see https://stackoverflow.com/a/60184319/9285308

      - name: add npmrc token
        run: |
          echo "@gemunion:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=$GITHUBTOKEN" >> .npmrc
          git update-index --assume-unchanged .npmrc
        env:
          GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}

#      - name: Authenticate check via npm npmjs.org
#        run: npm whoami
      - name: Authenticate check via npm pkg.github
        run: npm whoami --registry=https://npm.pkg.github.com/

      - name: Install Packages npm i
        run: npm i

      - name: Bootstrap Packages
        run: npm run bootstrap

      - name: Authenticate Registry & Configure Git User
        run: |
          npx npm-cli-login -u $GITHUBUSER -p $GITHUBTOKEN -e $GITHUBEMAIL -r https://npm.pkg.github.com -s @gemunion --config-path="./"
          git config --global user.name 'trejgun'
          git config --global user.email $GITHUBEMAIL
        env:
          GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}
          GITHUBUSER: ${{ secrets.GITHUBUSER }}
          GITHUBEMAIL: ${{ secrets.GITHUBEMAIL }}
#
#      - name: Authenticate check via npm npmjs.org
#        run: npm whoami
      - name: Authenticate check via npm pkg.github
        run: npm whoami --registry=https://npm.pkg.github.com/
#
      - name: Obfuscate and Rename
        run: npm run obfuscate && find . -name '*obfuscated.js' -exec bash -c 'mv "$1" "${1/-obfuscated/}"' _ {} \;

      - name: Version & Publish by lerna
        run: lerna version --force-publish --ignore-scripts && npm run release:publish -- --force-publish
        env:
          GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}
